server:
  port: 5555
---

spring:
  profiles: development
server:
  port: 5555

---

spring:
  profiles: production
server:
  port: 0

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org
